import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Header } from 'grommet'
import Link from 'next/link'

import MainSection from '../components/mainSection';


export default function Home() {
  return (

    <div className={styles.container}>
   
      <Head>
        <title>Unhash Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MainSection/>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Unhash Labs</a>
        </h1>

        <p className={styles.description}>
         Check out what we do...
        </p>

        <div className={styles.grid}>
          

          <Link href='/MetaswapNft'>
          <a className={styles.card}>
            <h2>Metaswap &rarr;</h2>
            
            <p>Our green NFT marketplace on the Hedera network. 

            </p>
            </a>
          </Link>
          
     
          <Link  href="/VintageInspired" >
          <a className={styles.card}>
            <h2>Vintage Inspired &rarr;</h2>
            <p>Our fashion company focusing on forward thinking inovation within the fashion industry. </p>
          </a>
          </Link>

          <Link href="/UnhashInsider" >
          <a
            
            className={styles.card}
          >
            <h2>Unhash Insider &rarr;</h2>
            <p>Our research focused Cryptocurrency & WEB3 Education platform.</p>
          </a>
          </Link>
          <Link  href="/Build" >
        
          <a
      
            className={styles.card}
          >
            <h2>Build &rarr;</h2>
            <p>
              We help people make the world a better place with quality software. Book a free consultation service to see if our team may be able to help you today. 
            </p>
          </a>
          </Link>
        </div>
      </main>



   
    </div>
 
  )
}
